title: "Ali Nikkhah"
email: "alinkkh9@gmail.com"
description: >-
  Applied-machine-learning researcher and engineering lead transforming state-of-the-art methods into robust, production-grade systems.
baseurl: ""
url: "https://alinikkhah2001.github.io"
linkedin_username: "alinikkhah2001"
github_username: "AliNikkhah2001"
theme: minima
